---
- name: Determine which templates to deploy
  ansible.builtin.set_fact:
    __target_images: >-
      {{
        __proxmox_cloudinit_images
        if (proxmox_target | lower == 'all')
        else (
          __proxmox_cloudinit_images
          | selectattr('name', 'in', proxmox_target.split(',') | map('trim') | list)
          | list
        )
      }}

- name: Fail if any requested template is missing
  ansible.builtin.fail:
    msg: "The following requested templates were not found: {{ __missing_templates | join(', ') }}"
  vars:
    __req_templates: "{{ proxmox_target.split(',') | map('trim') | list }}"
    __found_templates: "{{ __target_images | map(attribute='name') | list }}"
    __missing_templates: "{{ __req_templates | difference(__found_templates) }}"
  when:
    - proxmox_target | default('all') | lower != 'all'
    - __missing_templates | length > 0

- name: Install proxmoxer
  ansible.builtin.apt:
    name: python3-proxmoxer
    state: present

- name: Remove existsing templates
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    name: "{{ item.name }}-tmp"
    state: absent
  loop: "{{ __target_images }}"
  loop_control:
    label: "{{ item.name }}"

- name: Download cloud-init images to Proxmox storage
  ansible.builtin.get_url:
    url: "{{ item.image_url }}/{{ item.image_name }}"
    dest: "{{ __proxmox_downloads_dir }}/{{ item.image_name }}"
    mode: '0644'
  loop: "{{ __target_images }}"
  loop_control:
    label: "{{ item.name }}"
  tags: download

- name: Apply Cloud-Init configs from templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/lib/vz/snippets/{{ item }}"
    mode: '0644'
  loop: "{{ __target_images | map(attribute='cloudinit_config') | unique | list }}"

- name: Create virtual machine
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ proxmox_node }}"
    name: "{{ item.name }}-tmp"
    memory: "{{ __proxmox_vm_memory }}"
    cpu: "{{ __proxmox_vm_cpu_type }}"
    cores: "{{ __proxmox_vm_cpu_cores }}"
    ostype: "{{ __proxmox_vm_os_type }}"
    net: "{{ proxmox_vm_network }}"
    serial: "{{ __proxmox_vm_serial }}"
    agent: "{{ __proxmox_vm_agent }}"
    scsihw: "{{ __proxmox_scsihw_model }}"
    bootdisk: "{{ __proxmox_disk_slot }}"
    boot: "order={{ __proxmox_disk_slot }}"
    ide: "{{ __proxmox_vm_ci_drive }}"
    cicustom: "user={{ __proxmox_name_storage }}:snippets/{{ item.cloudinit_config }}"
  loop: "{{ __target_images }}"
  loop_control:
    label: "{{ item.name }}"
  register: __proxmox_created_vms

- name: Import disk
  ansible.builtin.shell:
    cmd: >
      qm importdisk {{ item.vmid }}
      {{ __proxmox_downloads_dir }}/{{ item.item.image_name }}
      {{ __proxmox_name_storage }}
      --format {{ __proxmox_disk_format }}
  args:
    executable: /bin/bash
  register: __proxmox_import_disk
  changed_when: __proxmox_import_disk.rc == 0
  loop_control:
    label: "{{ item.item.name }}"
  loop: "{{ __proxmox_created_vms.results }}"

- name: Attach the disk to the VM
  ansible.builtin.shell:
    cmd: qm set {{ item.vmid }} --scsi0 {{ __proxmox_name_storage }}:{{ item.vmid }}/vm-{{ item.vmid }}-disk-0.{{ __proxmox_disk_format }}
  args:
    executable: /bin/bash
  register: __proxmox_attach_disk
  changed_when: __proxmox_attach_disk.rc == 0
  loop_control:
    label: "{{ item.item.name }}"
  loop: "{{ __proxmox_created_vms.results }}"

- name: Resize disk
  ansible.builtin.shell:
    cmd: qemu-img resize -f qcow2 /var/lib/vz/images/{{ item.vmid }}/vm-{{ item.vmid }}-disk-0.qcow2 {{ __proxmox_disk_size }}
  args:
    executable: /bin/bash
  changed_when: true
  loop_control:
    label: "{{ item.item.name }}"
  loop: "{{ __proxmox_created_vms.results }}"

- name: Update disk sizes
  ansible.builtin.shell:
    cmd: qm rescan
  args:
    executable: /bin/bash
  changed_when: true

- name: Convert VM to template
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.vmid }}"
    state: template
  loop_control:
    label: "{{ item.item.name }}"
  loop: "{{ __proxmox_created_vms.results }}"

- name: Clean up images from the Proxmox storage
  ansible.builtin.file:
    path: "{{ __proxmox_downloads_dir }}/{{ item }}"
    state: absent
  loop: "{{ __proxmox_created_vms.results | map(attribute='item.image_name') | list }}"
  tags: cleanup
